---
version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ğŸ”¼
    labels:
      - "type: dependency ğŸ”¼"
      - "type: documentation ğŸ“š"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ğŸ”¼
    labels:
      - "area: cicd ğŸ‘·â€â™‚ï¸"
      - "type: dependency ğŸ”¼"
